import type { FeatureProfile } from '../featureTypes'

export const FOSSIL_VALLEY_PROFILE: FeatureProfile = {
  id: 'fossil-valley',
  displayName: 'Fossil Valley',
  triggerSymbol: 'footprint',
  triggerDisplayName: 'Fossil Footprints',
  theme: 'fossil',
  startingRespins: 3,
  boardWidth: 5,
  boardHeight: 5,
  hitGeneration: {
    hitProbability: 0.36,
    multiHitProbability: 0,
    maxTilesPerHit: 1,
  },
  collectorProbability: 0,
  collectors: [],
  jackpotProbability: 0,
  jackpotWeights: [],
  tileTable: [
    {
      id: 'small-fossil',
      displayName: 'Small Fossil',
      rarity: 'common',
      rarityWeight: 10,
      payoutValue: 6,
      discoveryCategory: 'fossil',
      progressionContribution: { sectionId: 'limbs', pieces: 1 },
    },
    {
      id: 'amber',
      displayName: 'Amber',
      rarity: 'common',
      rarityWeight: 5,
      payoutValue: 12,
      discoveryCategory: 'mineral',
      classificationTag: 'amber-sample',
    },
    {
      id: 'footprints',
      displayName: 'Footprints',
      rarity: 'common',
      rarityWeight: 5,
      payoutValue: 12,
      discoveryCategory: 'evidence',
      classificationTag: 'trackway',
    },
    {
      id: 'fern',
      displayName: 'Fern',
      rarity: 'common',
      rarityWeight: 4,
      payoutValue: 18,
      discoveryCategory: 'flora',
    },
    {
      id: 'river',
      displayName: 'River',
      rarity: 'common',
      rarityWeight: 4,
      payoutValue: 18,
      discoveryCategory: 'terrain',
    },
    {
      id: 'nest',
      displayName: 'Nest',
      rarity: 'uncommon',
      rarityWeight: 2,
      payoutValue: 18,
      discoveryCategory: 'evidence',
      classificationTag: 'nest-site',
    },
    {
      id: 'bone-cluster',
      displayName: 'Bone Cluster',
      rarity: 'uncommon',
      rarityWeight: 5,
      payoutValue: 24,
      discoveryCategory: 'fossil',
      progressionContribution: { sectionId: 'spine', pieces: 1 },
    },
    {
      id: 'dinosaur-egg',
      displayName: 'Dinosaur Egg',
      rarity: 'uncommon',
      rarityWeight: 5,
      payoutValue: 24,
      discoveryCategory: 'evidence',
      classificationTag: 'egg-clutch',
    },
    {
      id: 'complete-skeleton',
      displayName: 'Complete Skeleton',
      rarity: 'rare',
      rarityWeight: 4,
      payoutValue: 30,
      discoveryCategory: 'fossil',
      progressionContribution: { sectionId: 'skull', pieces: 1 },
    },
    {
      id: 'living-specimen',
      displayName: 'Living Specimen',
      rarity: 'rare',
      rarityWeight: 4,
      payoutValue: 30,
      discoveryCategory: 'life',
      classificationTag: 'living-evidence',
    },
    {
      id: 'new-species',
      displayName: 'New Species',
      rarity: 'legendary',
      rarityWeight: 2,
      payoutValue: 30,
      discoveryCategory: 'species',
      progressionContribution: { sectionId: 'tail', pieces: 1 },
      classificationTag: 'new-species',
    },
  ],
  progression: {
    id: 'fossil-assembly',
    displayName: 'Unknown Specimen',
    sections: [
      { id: 'skull', displayName: 'Skull', requiredPieces: 2, completionBonus: 8 },
      { id: 'spine', displayName: 'Spine', requiredPieces: 2, completionBonus: 8 },
      { id: 'limbs', displayName: 'Limbs', requiredPieces: 3, completionBonus: 6 },
      { id: 'tail', displayName: 'Tail', requiredPieces: 2, completionBonus: 6 },
    ],
    fullCompletionBonus: 20,
    classificationRules: [
      {
        id: 'trace-fossil',
        displayName: 'Trace Fossil',
        requiredTags: ['trackway'],
        bonus: 2,
      },
      {
        id: 'nesting-specimen',
        displayName: 'Nesting Specimen',
        requiredTags: ['nest-site', 'egg-clutch'],
        bonus: 6,
      },
      {
        id: 'amber-preserved-specimen',
        displayName: 'Amber-Preserved Specimen',
        requiredTags: ['amber-sample', 'trackway'],
        bonus: 8,
      },
      {
        id: 'living-descendant',
        displayName: 'Living Descendant Evidence',
        requiredTags: ['living-evidence'],
        bonus: 12,
      },
      {
        id: 'new-species',
        displayName: 'New Species Candidate',
        requiredTags: ['new-species'],
        bonus: 18,
      },
    ],
  },
  payoutRules: {
    tileValueMultiplier: 0.56,
    collectorCollectsExistingTiles: true,
    hitResetsRespinsTo: 3,
  },
  completionReward: 0,
}
