import type { FeatureProfile } from '../featureTypes'

export const NESTING_GROUNDS_PROFILE: FeatureProfile = {
  id: 'nesting-grounds',
  displayName: 'Nesting Grounds',
  triggerSymbol: 'nestingEggs',
  triggerDisplayName: 'Nesting Eggs',
  theme: 'nesting',
  startingRespins: 3,
  boardWidth: 5,
  boardHeight: 5,
  hitGeneration: {
    hitProbability: 0.55,
    multiHitProbability: 0.42,
    maxTilesPerHit: 3,
  },
  collectorProbability: 0,
  collectors: [],
  jackpotProbability: 0,
  jackpotWeights: [],
  tileTable: [
    {
      id: 'fern',
      displayName: 'Fern',
      rarity: 'common',
      rarityWeight: 10,
      payoutValue: 2,
      discoveryCategory: 'habitat',
    },
    {
      id: 'river',
      displayName: 'River',
      rarity: 'common',
      rarityWeight: 8,
      payoutValue: 3,
      discoveryCategory: 'habitat',
    },
    {
      id: 'footprints',
      displayName: 'Footprints',
      rarity: 'common',
      rarityWeight: 7,
      payoutValue: 3,
      discoveryCategory: 'life',
      classificationTag: 'movement',
    },
    {
      id: 'nest',
      displayName: 'Nest',
      rarity: 'common',
      rarityWeight: 7,
      payoutValue: 4,
      discoveryCategory: 'nest',
      progressionContribution: { sectionId: 'nest-sites', pieces: 1 },
      classificationTag: 'nest-site',
    },
    {
      id: 'egg',
      displayName: 'Egg',
      rarity: 'common',
      rarityWeight: 10,
      payoutValue: 4,
      discoveryCategory: 'egg',
      progressionContribution: { sectionId: 'eggs-found', pieces: 1 },
      classificationTag: 'egg',
    },
    {
      id: 'family-nest',
      displayName: 'Family Nest',
      rarity: 'uncommon',
      rarityWeight: 4,
      payoutValue: 9,
      discoveryCategory: 'nest',
      progressionContribution: { sectionId: 'nest-sites', pieces: 1 },
      classificationTag: 'family-nest',
    },
    {
      id: 'juvenile-dinosaur',
      displayName: 'Juvenile Dinosaur',
      rarity: 'rare',
      rarityWeight: 2,
      payoutValue: 18,
      discoveryCategory: 'life',
      progressionContribution: { sectionId: 'young-observed', pieces: 1 },
      classificationTag: 'juvenile',
    },
    {
      id: 'nesting-colony',
      displayName: 'Nesting Colony',
      rarity: 'legendary',
      rarityWeight: 1,
      payoutValue: 42,
      discoveryCategory: 'colony',
      progressionContribution: { sectionId: 'colony-confirmed', pieces: 1 },
      classificationTag: 'colony',
    },
  ],
  tileEvolution: [
    {
      fromTileId: 'egg',
      probability: 0.34,
      toTile: {
        id: 'hatchling',
        displayName: 'Hatchling',
        rarity: 'uncommon',
        rarityWeight: 0,
        payoutValue: 18,
        discoveryCategory: 'life',
        progressionContribution: { sectionId: 'hatchlings', pieces: 1 },
        classificationTag: 'hatchling',
      },
    },
  ],
  progression: {
    id: 'nesting-life-cycle',
    displayName: 'Nesting Life Cycle',
    sections: [
      { id: 'nest-sites', displayName: 'Nest Sites', requiredPieces: 3, completionBonus: 4 },
      { id: 'eggs-found', displayName: 'Eggs Found', requiredPieces: 3, completionBonus: 4 },
      { id: 'hatchlings', displayName: 'Hatchlings', requiredPieces: 2, completionBonus: 10 },
      { id: 'young-observed', displayName: 'Young Observed', requiredPieces: 1, completionBonus: 8 },
      {
        id: 'colony-confirmed',
        displayName: 'Colony Confirmed',
        requiredPieces: 1,
        completionBonus: 18,
      },
    ],
    fullCompletionBonus: 12,
    classificationRules: [
      {
        id: 'active-nest',
        displayName: 'Active Nest',
        requiredTags: ['egg', 'nest-site'],
        bonus: 2,
      },
      {
        id: 'hatching-ground',
        displayName: 'Hatching Ground',
        requiredTags: ['egg', 'hatchling'],
        bonus: 8,
      },
      {
        id: 'living-colony',
        displayName: 'Living Colony',
        requiredTags: ['hatchling', 'juvenile'],
        bonus: 12,
      },
      {
        id: 'nesting-colony',
        displayName: 'Nesting Colony',
        requiredTags: ['colony'],
        bonus: 20,
      },
    ],
  },
  payoutRules: {
    tileValueMultiplier: 0.44,
    collectorCollectsExistingTiles: true,
    hitResetsRespinsTo: 3,
  },
  completionReward: 0,
}
