import type { FeatureProfile } from '../featureTypes'

export const PREDATOR_VALLEY_PROFILE: FeatureProfile = {
  id: 'predator-valley',
  displayName: 'Predator Valley',
  triggerSymbol: 'predatorTracks',
  triggerDisplayName: 'Predator Tracks',
  theme: 'predator',
  startingRespins: 3,
  boardWidth: 5,
  boardHeight: 5,
  hitGeneration: {
    hitProbability: 0.38,
    multiHitProbability: 0.2,
    maxTilesPerHit: 3,
  },
  collectorProbability: 0,
  collectors: [],
  jackpotProbability: 0,
  jackpotWeights: [],
  tileTable: [
    {
      id: 'fresh-tracks',
      displayName: 'Fresh Tracks',
      rarity: 'common',
      rarityWeight: 10,
      payoutValue: 3,
      discoveryCategory: 'clue',
      progressionContribution: { sectionId: 'initial-scan', pieces: 1 },
      classificationTag: 'tracks',
    },
    {
      id: 'broken-branches',
      displayName: 'Broken Branches',
      rarity: 'common',
      rarityWeight: 8,
      payoutValue: 4,
      discoveryCategory: 'clue',
      progressionContribution: { sectionId: 'signs-detected', pieces: 1 },
    },
    {
      id: 'scat-sample',
      displayName: 'Scat Sample',
      rarity: 'common',
      rarityWeight: 6,
      payoutValue: 5,
      discoveryCategory: 'clue',
      progressionContribution: { sectionId: 'signs-detected', pieces: 1 },
      classificationTag: 'feeding-sign',
    },
    {
      id: 'feather',
      displayName: 'Feather',
      rarity: 'common',
      rarityWeight: 5,
      payoutValue: 7,
      discoveryCategory: 'clue',
      classificationTag: 'feather',
    },
    {
      id: 'claws',
      displayName: 'Claws',
      rarity: 'uncommon',
      rarityWeight: 5,
      payoutValue: 10,
      discoveryCategory: 'clue',
      progressionContribution: { sectionId: 'trail-emerging', pieces: 1 },
      classificationTag: 'claws',
    },
    {
      id: 'blood-trail',
      displayName: 'Blood Trail',
      rarity: 'uncommon',
      rarityWeight: 4,
      payoutValue: 14,
      discoveryCategory: 'trail',
      progressionContribution: { sectionId: 'trail-emerging', pieces: 1 },
      classificationTag: 'blood-trail',
    },
    {
      id: 'footprint-pattern',
      displayName: 'Footprint Pattern',
      rarity: 'uncommon',
      rarityWeight: 4,
      payoutValue: 18,
      discoveryCategory: 'trail',
      progressionContribution: { sectionId: 'close', pieces: 1 },
      classificationTag: 'pattern',
    },
    {
      id: 'nest-site',
      displayName: 'Nest Site',
      rarity: 'rare',
      rarityWeight: 3,
      payoutValue: 24,
      discoveryCategory: 'territory',
      classificationTag: 'nest-site',
    },
    {
      id: 'den-entrance',
      displayName: 'Den Entrance',
      rarity: 'rare',
      rarityWeight: 2,
      payoutValue: 38,
      discoveryCategory: 'territory',
      progressionContribution: { sectionId: 'close', pieces: 1 },
      classificationTag: 'den-entrance',
    },
    {
      id: 'predator-encounter',
      displayName: 'Predator Encounter',
      rarity: 'legendary',
      rarityWeight: 1,
      payoutValue: 80,
      discoveryCategory: 'encounter',
      progressionContribution: { sectionId: 'predator-located', pieces: 1 },
      classificationTag: 'predator-located',
    },
  ],
  progression: {
    id: 'tracking-confidence',
    displayName: 'Tracking Confidence',
    sections: [
      { id: 'initial-scan', displayName: 'Initial Scan', requiredPieces: 1, completionBonus: 2 },
      { id: 'signs-detected', displayName: 'Signs Detected', requiredPieces: 2, completionBonus: 4 },
      { id: 'trail-emerging', displayName: 'Trail Emerging', requiredPieces: 2, completionBonus: 5 },
      { id: 'close', displayName: 'Close', requiredPieces: 2, completionBonus: 7 },
      {
        id: 'predator-located',
        displayName: 'Predator Located',
        requiredPieces: 1,
        completionBonus: 16,
      },
    ],
    fullCompletionBonus: 10,
    classificationRules: [
      {
        id: 'signs-detected',
        displayName: 'Signs Detected',
        requiredTags: ['tracks'],
        bonus: 1,
      },
      {
        id: 'trail-confirmed',
        displayName: 'Trail Confirmed',
        requiredTags: ['tracks', 'feeding-sign'],
        bonus: 3,
      },
      {
        id: 'territory-identified',
        displayName: 'Territory Identified',
        requiredTags: ['nest-site', 'den-entrance'],
        bonus: 6,
      },
      {
        id: 'predator-located',
        displayName: 'Predator Located',
        requiredTags: ['predator-located'],
        bonus: 18,
      },
    ],
  },
  payoutRules: {
    tileValueMultiplier: 0.56,
    collectorCollectsExistingTiles: true,
    hitResetsRespinsTo: 3,
  },
  completionReward: 0,
}
