import type { FeatureProfile } from '../featureTypes'

export const FOSSIL_VALLEY_PROFILE: FeatureProfile = {
  id: 'fossil-valley',
  displayName: 'Fossil Valley',
  startingRespins: 3,
  boardWidth: 5,
  boardHeight: 5,
  hitGeneration: {
    hitProbability: 0.36,
    multiHitProbability: 0,
    maxTilesPerHit: 1,
  },
  collectorProbability: 0,
  collectors: [],
  jackpotProbability: 0,
  jackpotWeights: [],
  tileTable: [
    {
      id: 'small-fossil',
      displayName: 'Small Fossil',
      rarity: 'common',
      rarityWeight: 10,
      payoutValue: 6,
      discoveryCategory: 'fossil',
    },
    {
      id: 'amber',
      displayName: 'Amber',
      rarity: 'common',
      rarityWeight: 5,
      payoutValue: 12,
      discoveryCategory: 'mineral',
    },
    {
      id: 'footprints',
      displayName: 'Footprints',
      rarity: 'common',
      rarityWeight: 5,
      payoutValue: 12,
      discoveryCategory: 'evidence',
    },
    {
      id: 'fern',
      displayName: 'Fern',
      rarity: 'common',
      rarityWeight: 4,
      payoutValue: 18,
      discoveryCategory: 'flora',
    },
    {
      id: 'river',
      displayName: 'River',
      rarity: 'common',
      rarityWeight: 4,
      payoutValue: 18,
      discoveryCategory: 'terrain',
    },
    {
      id: 'nest',
      displayName: 'Nest',
      rarity: 'uncommon',
      rarityWeight: 2,
      payoutValue: 18,
      discoveryCategory: 'evidence',
    },
    {
      id: 'bone-cluster',
      displayName: 'Bone Cluster',
      rarity: 'uncommon',
      rarityWeight: 5,
      payoutValue: 24,
      discoveryCategory: 'fossil',
    },
    {
      id: 'dinosaur-egg',
      displayName: 'Dinosaur Egg',
      rarity: 'uncommon',
      rarityWeight: 5,
      payoutValue: 24,
      discoveryCategory: 'evidence',
    },
    {
      id: 'complete-skeleton',
      displayName: 'Complete Skeleton',
      rarity: 'rare',
      rarityWeight: 4,
      payoutValue: 30,
      discoveryCategory: 'fossil',
    },
    {
      id: 'living-specimen',
      displayName: 'Living Specimen',
      rarity: 'rare',
      rarityWeight: 4,
      payoutValue: 30,
      discoveryCategory: 'life',
    },
    {
      id: 'new-species',
      displayName: 'New Species',
      rarity: 'legendary',
      rarityWeight: 2,
      payoutValue: 30,
      discoveryCategory: 'species',
    },
  ],
  payoutRules: {
    tileValueMultiplier: 1,
    collectorCollectsExistingTiles: true,
    hitResetsRespinsTo: 3,
  },
  completionReward: 0,
}
